dist: xenial
language: php
php:
  - '7.2'
services:
  - mysql
before_script:
  - cp .env.travis .env
  - composer self-update
  - composer install --no-interaction
  - npm install
  - mysql -e 'create database homestead;'
  - php artisan migrate
  - php artisan key:generate
script:
  - composer cs-check-all
  - composer check-name
  - npm run prod
