dist: xenial
language: php
php:
- '7.2'
services:
- mysql
before_script:
- cp .env.travis .env
- composer self-update
- composer install --no-interaction
- npm install
- mysql -e 'create database homestead;'
- php artisan migrate
- php artisan key:generate
script:
- composer cs-check-all
- composer check-name
- npm run prod
cache:
  directories:
  - node_modules
  - vendor
before_install:
- openssl aes-256-cbc -K $encrypted_4bcf1a01802b_key -iv $encrypted_4bcf1a01802b_iv
  -in .travis/healthonline.enc -out .travis/healthonline -d
- eval "$(ssh-agent -s)"
- cp .travis/healthonline ~/.ssh/healthonline
- chmod 600 ~/.ssh/healthonline
- ssh-add ~/.ssh/healthonline
deploy:
- provider: script
  skip_cleanup: true
  script: ".travis/deploy_staging.sh"
  on:
    branch: master
